name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'dist/*.js' ]

jobs:
  deploy-action-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install depenedencies
        run: sudo npm i -g typescript @vercel/ncc
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.BOT_TOKEN}}
      - name: Generate action code
        run: npm run deploy
      - name: Configure repository
        run: |
          git config user.name "${{secrets.BOT_USERNAME}}"
          git config user.email "${{secrets.BOT_USERNAME}}@users.noreply.github.com"
      - name: Commit changes
        run: |
          if ! git diff --exit-code --quiet; then
            git add .
            git commit -m "[AUTO] Update generated code"
            git push
          fi

  test-defaults:
    needs: deploy-action-code
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: ^12.4
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@v1.5.0
        with:
          spm-package: __test__/TestProject
          scheme: TestProject-package
          action: test
          enable-code-coverage: true
          parallel-testing-enabled: true
      - uses: sersoft-gmbh/xcode-coverage-action@main
      - name: Check for produced coverage files
        run: test -d .xcodecov
        # We can't really check for more here, since we don't specify more.
